-- ECOMMERCE AUDIT 

---------------------------------------------------------- CUSTOMER TABLE------------------------------------------------------------------------------ 
-- TABLE VIEW

SELECT TOP  5 * FROM CUSTOMERS
-- ROWS COUNTS  

SELECT COUNT(*) AS TOTAL_ROWS FROM CUSTOMERS;

-- COLUMN COUNTS

SELECT COUNT(*) AS TOTAL_COLUMNS FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'CUSTOMERS';

-- COLUMN INFORMATION 

SELECT COLUMN_NAME , DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'CUSTOMERS';

-- DUPLICATE CHECKS 
SELECT customer_id , COUNT(*) FROM CUSTOMERS
GROUP BY customer_id
HAVING COUNT(*)>1;

SELECT customer_unique_id , COUNT(*) FROM CUSTOMERS
GROUP BY customer_unique_id
HAVING COUNT(*)>1;

-- ONE CUSTOMER HAVE MANY ACCOUNT 

-- TOTAL UNIQUE CUSTOMERS 
SELECT COUNT(DISTINCT customer_unique_id) AS TOTAL_CUSTOMERS FROM CUSTOMERS

-- MISSING VALUES 
SELECT 
SUM(CASE WHEN customer_id IS NULL THEN 1 ELSE 0 END) AS CUSTOMER_ID_NULL,
SUM(CASE WHEN customer_unique_id IS NULL THEN 1 ELSE 0 END) AS CUSTOMER_UNIQUE_ID_NULL,
SUM(CASE WHEN customer_zip_code_prefix IS NULL THEN 1 ELSE 0 END ) AS CUSTOMER_ZIP_CODE_NULL,
SUM(CASE WHEN customer_city IS NULL THEN 1 ELSE 0 END ) AS CUSTOMER_CITY_NULL,
SUM(CASE WHEN customer_city IS NULL THEN 1 ELSE 0 END ) AS CUSTOMER_CITY_NULL
FROM CUSTOMERS;

-- ZIPCODE PREFIX CHECK 

SELECT C.customer_id FROM CUSTOMERS AS C
LEFT JOIN GEO_LOCATION AS G
ON  C.customer_zip_code_prefix = G.geolocation_zip_code_prefix
WHERE C.customer_id IS NULL 

-- ZERO


-------------------------------------------------------- ORDER TABLE ----------------------------------------------------------------------------------- 
--TABLE VIEW 

SELECT TOP 5 * FROM ORDERS 

-- ROWS COUNT 

SELECT COUNT(*) AS TOTAL_ROWS FROM ORDERS;

-- COLUMNS COUNT

SELECT COUNT(*) AS TOTAL_COLUMNS FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ORDERS';

-- COLUMN INFORMATION 

SELECT  COLUMN_NAME , DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ORDERS';

-- DUPLICATE 

SELECT ORDER_ID  , COUNT(*) AS DUPLICATE_ORDER FROM ORDERS
GROUP BY ORDER_ID
HAVING COUNT(*) > 1;

-- THERE IS NO DUPLICATE 

-- NULL VALUE CHECK 
SELECT 
SUM(CASE WHEN order_id IS NULL THEN 1 ELSE 0 END) AS ORDER_ID_NULL,
SUM(CASE WHEN customer_id IS NULL THEN 1 ELSE 0 END) AS CUSTOMER_ID_NULL,
SUM(CASE WHEN order_status IS NULL THEN 1 ELSE 0 END ) AS ORDER_STATUS_NULL,
SUM(CASE WHEN order_purchase_timestamp IS NULL THEN 1 ELSE 0 END ) AS ORDER_PURCAHSE_TIMESTAMP_NULL,
SUM(CASE WHEN order_approved_at IS NULL THEN 1 ELSE 0 END ) AS ORDER_APPROVED_AT_NULL,
SUM(CASE WHEN order_delivered_carrier_date IS NULL THEN 1 ELSE 0 END ) AS ORDER_DELIVERY_CARRIER_DATE_NULL,
SUM(CASE WHEN order_delivered_customer_date IS NULL THEN 1 ELSE 0 END ) AS ORDER_DELIVERY_CUSTOMER_DATE_NULL,
SUM(CASE WHEN order_estimated_delivery_date IS NULL THEN 1 ELSE 0 END ) AS ORDER_ESTIMATED_DELIVERY_DATE_NULL
FROM ORDERS;

/* -- NULL COLUMNS AND NUMBER

ORDER APPROVED 160
ORDER_DELIVERY_CARRIER_DATE 1783 
ORDER_DELIVERY_CUSTOMER_DATE 2965   

*/

-- ORDER STAUS DISTINCT 

SELECT DISTINCT order_status FROM ORDERS

-- INVALID ORDER_PURCHASE_TIMESTAMP

SELECT order_purchase_timestamp FROM ORDERS
WHERE TRY_CONVERT(datetime , order_purchase_timestamp) IS NULL AND order_purchase_timestamp IS NOT NULL;

-- INVALID ORDER APPROVED AT 

SELECT order_approved_at FROM ORDERS
WHERE TRY_CONVERT(datetime , order_approved_at) IS NULL AND order_approved_at IS NOT NULL ;


-- INVALID ORDER DELIVERY CARRIER DATE 

SELECT order_delivered_carrier_date FROM ORDERS
WHERE TRY_CONVERT(datetime , order_delivered_carrier_date) IS NULL AND order_delivered_carrier_date IS NOT NULL ;

-- INVALID ORDER DELIVERY CUSTOMER DATE 

SELECT order_delivered_customer_date FROM ORDERS
WHERE TRY_CONVERT(datetime ,  order_delivered_customer_date) IS NULL AND  order_delivered_customer_date IS NOT NULL ;

-- INVALID ORDER ESTIMATE DELIVERY DATE DATE 

SELECT order_estimated_delivery_date FROM ORDERS
WHERE TRY_CONVERT(datetime ,  order_estimated_delivery_date) IS NULL AND  order_estimated_delivery_date IS NOT NULL ;


-- NO ERROR IN ALL TABLE 


-------------------------------------------------------------ORDER ITEM TABLE --------------------------------------------------------------------------
-- TABLE VIEW 

SELECT TOP 5 * FROM ORDER_ITEMS

-- TOTAL ROWS 
SELECT COUNT(*) AS TOTAL_ROWS FROM ORDER_ITEMS ;

-- TOTAL COLUMNS 

SELECT COUNT(*) AS TOTAL_COLUMNS FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ORDER_ITEMS' ;

-- COLUMNS NAME AND DATA TYPES 

SELECT COLUMN_NAME , DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ORDER_ITEMS' ;

-- DUPLICATE CHECK

SELECT ORDER_ID , order_item_id,product_id , seller_id, COUNT(*) FROM ORDER_ITEMS
GROUP BY order_id ,order_item_id, product_id , seller_id
HAVING COUNT(*)>1 ;


-- NULL VALUE CHECK 
SELECT 
SUM(CASE WHEN order_id IS NULL THEN 1 ELSE 0 END) AS ORDER_ID_NULL,
SUM(CASE WHEN order_item_id IS NULL THEN 1 ELSE 0 END) AS order_item_id_NULL,
SUM(CASE WHEN product_id IS NULL THEN 1 ELSE 0 END ) AS product_id_NULL,
SUM(CASE WHEN seller_id IS NULL THEN 1 ELSE 0 END ) AS seller_id_NULL,
SUM(CASE WHEN shipping_limit_date IS NULL THEN 1 ELSE 0 END ) AS shipping_limit_date_NULL,
SUM(CASE WHEN price IS NULL THEN 1 ELSE 0 END ) AS price_NULL,
SUM(CASE WHEN freight_value IS NULL THEN 1 ELSE 0 END ) AS freight_value_NULL
FROM ORDER_ITEMS;


-- THERE IS NO NULL VALUE FOUNDS 


-- INVALID ORDER ITEM ID 

SELECT order_item_id FROM ORDER_ITEMS
WHERE TRY_CONVERT(INT , order_item_id) IS NULL AND order_item_id IS NOT NULL

-- INVALID SHIPPING LIMIT DATE 

SELECT shipping_limit_date FROM ORDER_ITEMS
WHERE TRY_CONVERT(datetime , shipping_limit_date) IS NULL AND shipping_limit_date IS NOT NULL

-- INVALID PRICE 

SELECT PRICE FROM ORDER_ITEMS
WHERE TRY_CONVERT(DECIMAL(10,2) ,PRICE) IS NULL AND PRICE IS NOT NULL 

-- INVALID FREIGHT VALUE 

SELECT freight_value FROM ORDER_ITEMS
WHERE TRY_CONVERT(decimal(10,2) ,freight_value) IS NULL AND freight_value IS NOT NULL 




---------------------------------------------------------- ORDER PAYMENT TABLE -----------------------------------------------------------------------
-- TABLE VIEW 

SELECT TOP 5 * FROM ORDER_PAYMENTS;

-- ROWS COUNT 
SELECT COUNT(*) AS TOTAL_ROWS FROM ORDER_PAYMENTS;

-- COLUMNS COUNT 
SELECT COUNT(*) AS TOTAL_COLUMNS FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME ='ORDER_PAYMENTS';

-- COLUMN NAME AND DATA TYPE 
SELECT COLUMN_NAME , DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='ORDER_PAYMENTS';

-- DUPLICATE CHECKS 
SELECT order_id , payment_sequential , payment_type , payment_installments , payment_value, COUNT(*) FROM ORDER_PAYMENTS
GROUP BY order_id , payment_sequential , payment_type , payment_installments , payment_value
HAVING COUNT(*)>1;

-- NULL VALUE CHECK  
SELECT 
SUM(CASE WHEN order_id IS NULL THEN 1 ELSE 0 END) AS ORDER_ID_NULL,
SUM(CASE WHEN payment_sequential IS NULL THEN 1 ELSE 0 END) AS payment_sequential_NULL,
SUM(CASE WHEN payment_type IS NULL THEN 1 ELSE 0 END ) AS payment_type_NULL,
SUM(CASE WHEN payment_installments IS NULL THEN 1 ELSE 0 END ) AS payment_installments_NULL,
SUM(CASE WHEN payment_value IS NULL THEN 1 ELSE 0 END ) AS payment_value_NULL
FROM ORDER_PAYMENTS;

-- DISTICT PAYMENT TYPE 
SELECT DISTINCT PAYMENT_TYPE FROM ORDER_PAYMENTS

-- INVALID PAYMENT VALUE DATA TYPES

SELECT * FROM ORDER_PAYMENTS 
WHERE TRY_CONVERT(DECIMAL(10,2),payment_value) IS NULL

-- ZERO ERROR


------------------------------------------------------------- ORDER REVIEW RATING TABLE ---------------------------------------------------------------
-- TABLE VIEW 

SELECT TOP 5 * FROM ORDER_REVIEW_RATINGS

-- ROWS COUNT 

SELECT COUNT(*) AS TOTAL_ROWS FROM ORDER_REVIEW_RATINGS;

-- COLUMN COUNT 

SELECT COUNT(*) AS TOTAL_COLUMNS FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ORDER_REVIEW_RATINGS' ;

-- COLUMN NAME AND DATA TYPE 

SELECT COLUMN_NAME , DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ORDER_REVIEW_RATINGS' ;

-- DUPICATES CHECK 

SELECT REVIEW_ID ,order_id, COUNT(*) FROM ORDER_REVIEW_RATINGS
GROUP BY REVIEW_ID ,order_id
HAVING COUNT(*)>1

-- NO DUPLICATES 

-- NULL VALUE CHECK  
SELECT 
SUM(CASE WHEN review_id IS NULL THEN 1 ELSE 0 END) AS REVIEW_ID_NULL,
SUM(CASE WHEN order_id IS NULL THEN 1 ELSE 0 END) AS order_id_NULL,
SUM(CASE WHEN review_score IS NULL THEN 1 ELSE 0 END ) AS review_score_NULL,
SUM(CASE WHEN review_creation_date IS NULL THEN 1 ELSE 0 END ) AS review_creation_date_NULL,
SUM(CASE WHEN review_answer_timestamp IS NULL THEN 1 ELSE 0 END ) AS review_answer_timestamp_NULL
FROM ORDER_REVIEW_RATINGS; 

-- NO NULL VALUES 

-- INVALID REVIEW SCORE 

SELECT review_score FROM ORDER_REVIEW_RATINGS
WHERE TRY_CONVERT(INT, review_score) IS NULL ;

-- INVALID REVIEW CREATION DATE 

SELECT review_creation_date FROM ORDER_REVIEW_RATINGS
WHERE TRY_CONVERT(datetime, review_creation_date) IS NULL ;

-- INVALID REVIEW ANSWER TIMESTAMP 

SELECT review_answer_timestamp FROM ORDER_REVIEW_RATINGS
WHERE TRY_CONVERT(datetime, review_answer_timestamp) IS NULL ;

-- NO ERROR IN CONVERT  ALL COLUMNS 

-- DISTICT REVIEW SCORE 

SELECT DISTINCT review_score FROM ORDER_REVIEW_RATINGS;


---------------------------------------------------------------- Product Table ------------------------------------------------------------------------
-- TABLE VIEW 
select top 5 * from PRODUCTS

-- ROWS COUNT 

SELECT COUNT(*) AS TOTAL_ROWS FROM PRODUCTS

-- COLUMNS COUNT 

SELECT COUNT(*) AS TOTAL_COLUMNS FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PRODUCTS'

-- COLUMNS NAME AND DATA TYPE 
SELECT COLUMN_NAME , DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PRODUCTS'

-- DUPLICATES CHECK 

SELECT PRODUCT_ID AS PRODUCT_ID_DUPLICATED FROM PRODUCTS
GROUP BY PRODUCT_ID
HAVING COUNT(*) > 1

-- NULLS VALUE CHECK 

SELECT 
SUM(CASE WHEN product_id IS NULL THEN 1 ELSE 0 END) AS PRODUCT_ID_NULL,
SUM(CASE WHEN product_category_name IS NULL THEN 1 ELSE 0 END) AS product_category_name_NULL,
SUM(CASE WHEN product_name_lenght IS NULL THEN 1 ELSE 0 END ) AS product_name_lenght_NULL,
SUM(CASE WHEN product_description_lenght IS NULL THEN 1 ELSE 0 END ) AS product_description_lenght_NULL,
SUM(CASE WHEN product_photos_qty IS NULL THEN 1 ELSE 0 END) AS product_photos_qty_NULL ,
SUM(CASE WHEN product_weight_g IS NULL THEN 1 ELSE 0 END) AS product_weight_g_NULL,
SUM(CASE WHEN product_length_cm IS NULL THEN 1 ELSE 0 END ) AS product_length_cm_NULL,
SUM(CASE WHEN product_height_cm IS NULL THEN 1 ELSE 0 END ) AS product_height_cm_NULL,
SUM(CASE WHEN product_width_cm IS NULL THEN 1 ELSE 0 END) AS product_width_cm_NULL
FROM PRODUCTS

-- DISTICT PRODUCT CATEGORY 

SELECT product_category_name FROM PRODUCTS
GROUP BY product_category_name



-------------------------------------------------------------------- SELLER TABLE ----------------------------------------------------------------------
-- TABLE VIEW 
SELECT TOP 5 * FROM SELLERS

-- ROWS COUNT 

SELECT COUNT(*) as TOTAL_ROWS FROM SELLERS

-- COLUMNS COUNT 

SELECT COUNT(*) AS COLUMNS_COUNT FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'SELLERS'

-- COLUMNS NAME AND DATA TYPES
SELECT COLUMN_NAME , DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'SELLERS'

-- NULL VALUE 

SELECT 
SUM(CASE WHEN seller_id IS NULL THEN 1 ELSE 0 END) AS seller_id_NULL,
SUM(CASE WHEN seller_zip_code_prefix IS NULL THEN 1 ELSE 0 END) AS seller_zip_code_prefix_NULL,
SUM(CASE WHEN seller_city IS NULL THEN 1 ELSE 0 END ) AS seller_city_NULL,
SUM(CASE WHEN seller_state IS NULL THEN 1 ELSE 0 END ) AS seller_state_NULL
FROM SELLERS

-- DISTINCT CHECK 

SELECT SELLER_ID , COUNT(*) AS DUPLICATES FROM SELLERS
GROUP BY SELLER_ID
HAVING COUNT(*) > 1


-------------------------------------------------------------GEO_LOCATION TABLE -----------------------------------------------------------------------

-- TABLE VIEW 
SELECT TOP 5 * FROM GEO_LOCATION

-- ROWS COUNT 
SELECT COUNT(*) AS TOTAL_ROWS FROM GEO_LOCATION

-- COLUMNS COUNT 
SELECT COUNT(*) AS TOTAL_COLUMNS FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'GEO_LOCATION'

-- COLUMNS NAME AND DATA TYPES 
SELECT COLUMN_NAME , DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'GEO_LOCATION'


-- NULL VALUE 

SELECT 
SUM(CASE WHEN geolocation_zip_code_prefix IS NULL THEN 1 ELSE 0 END) AS geolocation_zip_code_prefix_NULL,
SUM(CASE WHEN geolocation_lat IS NULL THEN 1 ELSE 0 END) AS geolocation_lat_NULL,
SUM(CASE WHEN geolocation_lng IS NULL THEN 1 ELSE 0 END ) AS geolocation_lng_NULL,
SUM(CASE WHEN geolocation_city IS NULL THEN 1 ELSE 0 END ) AS geolocation_city_NULL,
SUM(CASE WHEN geolocation_state IS NULL THEN 1 ELSE 0 END ) AS geolocation_state_NULL
FROM GEO_LOCATION

-- DUPLICATED CHECK

SELECT geolocation_zip_code_prefix , COUNT(*) FROM GEO_LOCATION
GROUP BY geolocation_zip_code_prefix
HAVING COUNT(*) > 1

-- DISTINCT STATE 

SELECT geolocation_state FROM GEO_LOCATION
GROUP BY geolocation_state



