-- TOTAL ORDER ID 

SELECT COUNT( DISTINCT order_id ) AS TOTAL_ORDERS FROM CLEAN.ORDERS_CLEAN ;

-- 99441

-- TOTAL CUSTOMER ID 

SELECT COUNT( DISTINCT customer_id ) AS TOTAL_CUSTOMERS FROM CLEAN.CUSTOMERS_CLEAN ;

-- 99441

-- REVENUE

SELECT SUM(price) AS TOTAL_REVENUE FROM CLEAN.ORDER_ITEMS_CLEAN ;

-- 13591643.70


-- AVERAGE ORDER VALUE

WITH ORDER_VALUE AS 
(
		SELECT order_id , SUM(price) AS ORDER_VALUES
		FROM CLEAN.ORDER_ITEMS_CLEAN
		GROUP BY order_id
)
SELECT AVG(ORDER_VALUES) AS AOV FROM ORDER_VALUE ;

-- AOV  137.754076

-- TOTAL SELLERS 

SELECT COUNT( DISTINCT SELLER_ID) AS TOTAL_SELLER FROM CLEAN.SELLERS_CLEAN

-- 3095

-- TOTAL PRODUCT

SELECT COUNT( DISTINCT product_id) AS TOTAL_PRODUCTS FROM CLEAN.PRODUCTS_CLEAN

-- 32951


-- MONTHLY ORDER AND REVENUE 

SELECT 
O.purchase_month_name ,
O.purchase_year,
COUNT (DISTINCT O.order_id) AS TOTAL_ORDERS,
SUM(OT.PRICE) AS TOTAL_REVENUE
FROM CLEAN.ORDERS_CLEAN O
INNER JOIN CLEAN.ORDER_ITEMS_CLEAN AS OT
ON O.order_id = OT.order_id
GROUP BY O.purchase_month , O.purchase_month_name , O.purchase_year
ORDER BY O.purchase_year , O.purchase_month ;

-- YEAR ORDER AND REVENUE 

SELECT 
O.purchase_year,
COUNT (DISTINCT O.order_id) AS TOTAL_ORDERS,
SUM(OT.PRICE) AS TOTAL_REVENUE
FROM CLEAN.ORDERS_CLEAN O
INNER JOIN CLEAN.ORDER_ITEMS_CLEAN AS OT
ON O.order_id = OT.order_id
GROUP BY  O.purchase_year
ORDER BY O.purchase_year ;



-- CUSTOMER ACQUISITION

WITH CUSTOMER_FIRST_PURCHASE AS 
(
	SELECT 
	C.customer_unique_id ,
	MIN(O.order_purchase_timestamp) AS FIRST_PURCHASE_DATE
	FROM CLEAN.ORDERS_CLEAN O
	INNER JOIN CLEAN.CUSTOMERS_CLEAN C
	ON O.customer_id = C.customer_id
	GROUP BY C.customer_unique_id
)
SELECT 
MONTH(FIRST_PURCHASE_DATE) AS PURCHASE_MONTH ,
YEAR(FIRST_PURCHASE_DATE) AS PURCHASE_YEAR ,
COUNT(*) AS NEW_CUSTOMERS 
FROM CUSTOMER_FIRST_PURCHASE
GROUP BY MONTH(FIRST_PURCHASE_DATE) ,
		 YEAR(FIRST_PURCHASE_DATE) 
ORDER BY PURCHASE_YEAR , PURCHASE_MONTH ;



-- NEW VS EXISTING CUSTOMERS REVENUE 

WITH CUSTOMER_ORDERS AS 
(
	SELECT 
	C.customer_unique_id,
	O.order_id ,
	CAST(O.order_purchase_timestamp AS DATE) AS order_purchase_date
	FROM CLEAN.ORDERS_CLEAN O
	JOIN CLEAN.CUSTOMERS_CLEAN C
	ON O.customer_id = C.customer_id
),
FIRST_PURCHASE AS 
(
	SELECT  
	customer_unique_id ,
	MIN(order_purchase_date) AS FIRST_PURCAHSE_DATE
	FROM CUSTOMER_ORDERS
	GROUP BY customer_unique_id
)

SELECT 

MONTH(CO.order_purchase_date) AS PURCHASE_MONTH,
YEAR(CO.order_purchase_date) AS PURCHASE_YEAR , 
CASE WHEN CO.order_purchase_date = FP.FIRST_PURCAHSE_DATE 
	THEN'NEW CUSTOMER' ELSE 'EXISTING CUSTOMER' END AS CUSTOMER_TYPE ,
SUM(OT.price) AS PRICE

FROM CUSTOMER_ORDERS CO
JOIN FIRST_PURCHASE FP
ON CO.customer_unique_id = FP.customer_unique_id
JOIN CLEAN.ORDER_ITEMS_CLEAN OT
ON CO.order_id = OT.order_id

GROUP BY 
		MONTH(CO.order_purchase_date) ,
		YEAR(CO.order_purchase_date)  , 
		CASE WHEN CO.order_purchase_date = FP.FIRST_PURCAHSE_DATE 
			THEN'NEW CUSTOMER' ELSE 'EXISTING CUSTOMER' END 
ORDER BY 
		PURCHASE_YEAR , PURCHASE_MONTH ;



-- REPEAT CUSTOMER 

WITH CUSTOMER_ORDERS AS (
					SELECT 
					C.customer_unique_id ,
					COUNT( O.order_id) AS TOTAL_ORDERS
					FROM CLEAN.ORDERS_CLEAN O
					JOIN CLEAN.CUSTOMERS_CLEAN AS C
					ON O.customer_id = C.customer_id
					GROUP BY C.customer_unique_id
					)
 SELECT COUNT(*) AS TOTAL_CUSTOMERS,
 SUM(CASE WHEN TOTAL_ORDERS = 1 THEN 1 ELSE 0 END) AS ONE_TIME_CUSTOMERS ,
 SUM(CASE WHEN TOTAL_ORDERS > 1 THEN 1 ELSE 0 END) AS REPEAT_CUSTOMERS
 FROM CUSTOMER_ORDERS  ;
 
-- CUSTOMER ORDER FREQUENCY 

WITH CUSTOMER_ORDERS AS (
						SELECT 
						C.customer_unique_id ,
						COUNT(O.order_id) AS TOTAL_ORDERS 
						FROM CLEAN.ORDERS_CLEAN O
						JOIN CLEAN.CUSTOMERS_CLEAN C
						ON O.customer_id = C.customer_id
						GROUP BY C.customer_unique_id
						) 
 SELECT TOTAL_ORDERS ,
 COUNT(*) AS TOTAL_CUSTOMERS
 FROM CUSTOMER_ORDERS
 GROUP BY TOTAL_ORDERS 
 ORDER BY TOTAL_ORDERS ;


 --PRODUCT EDA --

 -- REVENUE BY PRODUCT CATEGORY

 SELECT 
 P.product_category_name ,
 COUNT(DISTINCT OT.product_id) AS UNIQUE_PRODUCTS ,
 COUNT(DISTINCT OT.order_id) AS TOTAL_ORDERS ,
 COUNT(OT.order_id) AS TOTAL_ITEMS_SOLD , 
 SUM(OT.price) AS TOTAL_REVENUE 
 FROM CLEAN.ORDER_ITEMS_CLEAN  OT
 JOIN CLEAN.PRODUCTS_CLEAN P
 ON OT.product_id = P.product_id
 GROUP BY P.product_category_name
 ORDER BY TOTAL_REVENUE DESC;

-- TOP 10 CATEGORY_NAME 
 WITH PRODUCT_CATEGORY AS (
							SELECT 
							P.product_category_name ,
							COUNT(DISTINCT OT.order_id) AS TOTAL_ORDERS ,
							COUNT(OT.order_id) AS TOTAL_ITEMS_SOLD , 
							SUM(OT.price) AS TOTAL_REVENUE
							FROM CLEAN.ORDER_ITEMS_CLEAN  OT
							JOIN CLEAN.PRODUCTS_CLEAN P
							ON OT.product_id = P.product_id
							GROUP BY P.product_category_name
							)

SELECT TOP 10 product_category_name ,
TOTAL_REVENUE,
TOTAL_REVENUE * 100.0 / SUM(TOTAL_REVENUE) OVER() AS CATEGORY_REVENUE_CONTRIBUTION
FROM PRODUCT_CATEGORY 
ORDER BY TOTAL_REVENUE DESC ;






-- SELLER ANALYSIS 

-- TOP 10 SELLER  

SELECT TOP 10  S.seller_id , 
COUNT(DISTINCT OT.order_id) AS TOTAL_ORDERS ,
COUNT(*) AS TOTAL_ITEMS_SOLD ,
SUM(OT.price) AS TOTAL_REVENUE ,
AVG(OT.price) AS AVG_ITEM_PRICE 
FROM CLEAN.ORDER_ITEMS_CLEAN OT 
JOIN CLEAN.SELLERS_CLEAN S 
ON OT.seller_id = S.seller_id
GROUP BY S.seller_id
ORDER BY TOTAL_REVENUE DESC ;

 -- SELLER STATE REVENUE

 SELECT S.seller_state ,
 SUM(OT.price) AS STATE_TOTAL_REVENUE
 FROM CLEAN.ORDER_ITEMS_CLEAN OT
 JOIN CLEAN.SELLERS_CLEAN S
 ON OT.seller_id = S.seller_id
 GROUP BY S.seller_state
 ORDER BY STATE_TOTAL_REVENUE DESC ;


-- PAYMENT EDA 

SELECT 
payment_type ,
COUNT(*) AS TOTAL_PAYMENT_RECORD,
COUNT(DISTINCT order_id) AS TOTAL_ORDER ,
SUM(payment_value) AS TOTAL_PAYMENT ,
AVG(payment_value) AS AVG_PAYMENT 
FROM CLEAN.ORDER_PAYMENTS_CLEAN
GROUP BY payment_type
ORDER BY TOTAL_PAYMENT DESC ;

-- PAYMENT INSTALLMENT 

SELECT payment_installments , 
COUNT(DISTINCT order_id)  AS TOTAL_ORDERS ,
SUM(payment_value) AS TOTAL_PAYMENT
FROM CLEAN.ORDER_PAYMENTS_CLEAN
GROUP BY payment_installments 
ORDER BY payment_installments ;


-- REVIEW 

-- AVG RATING 

SELECT AVG(CAST(review_score AS DECIMAL(10,2))) AS AVG_RATING
FROM CLEAN.ORDER_REVIEW_RATINGS_CLEAN ;

SELECT review_score ,
COUNT (*) AS TOTAL_REVIEWS ,
COUNT (DISTINCT order_id) AS TOTAL_ORDERS 
FROM CLEAN.ORDER_REVIEW_RATINGS_CLEAN
GROUP BY review_score
ORDER BY review_score ;











